### PR TITLE
Adapter PS2 USB

### PR DESCRIPTION
**Pull request by Laddyacris**
Please make sure your PR is ready to be merged !
- [X] You added the changes in CHANGELOG.md
- [X] You choose the right repository branch to make the PR
- [X] You described the PR as below
- add usbhid for adapter ps2 GreenAsia

### CODE REVIEW

**Comment by substring** [comment]
can be merged, tested ok live today on IRC

**Comment by nadenislamarre** [comment]
but it doesnt disable the above xinmo value ?!?

**Comment by substring** [comment]
@nadenislamarre USBHID has been long ago set as a kernel module and not anymore inside the kernel so that we can add usbquirks in a single file. And it's all cumulative, no worries :) No need to edit kernel boot parameters anymore, whichever platform we run on :)

**Comment by nadenislamarre** [comment]
ok.

**Pull request merged**
