### PR TITLE
Add Dreamcast emulator : Reicast

### PR DESCRIPTION
**Pull request by substring**
Please make sure your PR is ready to be merged !
- [x] You added the changes in CHANGELOG.md
- [x] You choose the right repository branch to make the PR
- [x] You described the PR as below

Changes :
- add Reicast emulator

Fixes : https://github.com/recalbox/recalbox-os/issues/118

Related to (put here the others PR in other repositories)

### CODE REVIEW

**Comment by substring** [comment]
I hope it's complete ...
configgen on its way, probably tomorrow

**Comment by substring** [comment]
Roms directory added

**Comment by substring** [comment]
it used to compile fine against gcc 4.9, having some trouble with gcc5

**Comment by substring** [comment]
And we're good :)

**Comment by digitalLumberjack** [comment]
Really nice !

**Pull request merged**
