### PR TITLE
Rb 4.1.x nadenislamarre sshpassword

### PR DESCRIPTION
**Pull request by nadenislamarre**
Please make sure your PR is ready to be merged !
- [ ] You added the changes in CHANGELOG.md
- [x] You choose the right repository branch to make the PR
- [x] You described the PR as below

Changes :
- Randomize the ssh root password
- The ssh password can be updated
- The ssh password is visible on the es interface (see an other pr)
- not securing missing part : samba, manager 

Related to (put here the others PR in other repositories)

### CODE REVIEW

**Comment by nadenislamarre** [comment]
Some points :
- securing ssh without samba is not secure (you can modify allowed public keys)
- samba and manager will require the same password
- the password is saved in the /boot because i don't think it's nice to move it when sharing/copying usb keys (however, the password encoding is related to the pi hardware and a new one will be generated if not readable)
- the root password can be rewritten in clear in the /boot/recalbox-boot.conf file in case of emergency (so, from a computer)
- an option in system options => security will allow to enable/disable security, by default, off
  => security disabled should have the same effect as in 4.0, including setting the root password to recalboxroot
- the security parameter will not touch to kodi options. apple airplay control is enabled by default in kodi, without password. We should perhaps enable the http control (for remote phone applications) while some people don't enable it and don't understand why it doesn't work out of the box.

any other suggestion is welcome.

**Comment by digitalLumberjack** [comment]
Do you want me to add the option in ES system options ?

**Comment by nadenislamarre** [comment]
no.
i'll add things.
it's just that i'm doing it pr by pr to make less things to validate at a
time to make it easier for you (and for me).

**Comment by digitalLumberjack** [comment]
Cool

**Pull request merged**
