### PR TITLE
Fix and improvement for Moonlight

### PR DESCRIPTION
**Pull request by steak3**
[07/10/2015 beta8]
As autodiscovery was disabled to fix WiFi, and as moonlight config file breaks the commands:

Tutorial to run Moonlight for beta8 (part of #36) :

Activate Moonlight:
- Edit the file /roms/moonlight/**Moonlight.sh.hide_v2**: replace "YOUR_IP_HERE" by your PC address
- Rename this file from **Moonlight.sh.hide_v2** to **Moonlight.sh**

Initiliaze Moonlight (use SSH):
- Pairing the PC: **/recalbox/share/roms/moonlight/Moonlight.sh pair**
- Mapping the controller: **/recalbox/share/roms/moonlight/Moonlight.sh map**

Then, in EmulationStation, choose Moonlight system and launch Moonlight

For debug, uncomment the line 11 of Moonlight.sh

This is a temporary bypass to get Moonlight working from beta8. The best way to handle IP/pair/map steps should be integrating them to the UI.

---

[04/10/2015 beta7]
Tutorial here:
https://github.com/digitalLumberjack/recalbox-buildroot/pull/36

Deleted deprecated files with colon (:) inside the name. Allowing repository cloning in Windows (bug https://github.com/digitalLumberjack/recalbox-os/issues/449)

Fixed blackscreen on Moonlight.sh activation due to the theme format.

Added sound and background

Improved stream latency

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
You closed the pull request ? I wanted to add some of your features, but i already had modified the theme for the beta8 release. I wanted to check that for the next beta.

**Comment by steak3** [comment]
Je peux réouvrir si tu veux faire le tri dedans. Je comptais refaire un pull en prenant en compte la beta8 que je n'avais pas vu. Mais pour le coup il n'y a pas grand chose

[EDIT] Il n'y a pas de branche pour les betas? Ou j'ai mal compris sur quel code me synchroniser

**Comment by digitalLumberjack** [comment]
Ok cool :P

**Comment by steak3** [comment]
As autodiscovery was disabled to fix WiFi, and as moonlight config file breaks the commands:

Tutorial to run Moonlight for beta8 (part of #36) :

Activate Moonlight:
- Edit the file /roms/moonlight/**Moonlight.sh.hide_v2**: replace "YOUR_IP_HERE" by your PC address
- Rename this file from **Moonlight.sh.hide_v2** to **Moonlight.sh**

Initiliaze Moonlight (use SSH):
- Pairing the PC: **/recalbox/share/roms/moonlight/Moonlight.sh pair**
- Mapping the controller: **/recalbox/share/roms/moonlight/Moonlight.sh map**

Then, in EmulationStation, choose Moonlight system and launch Moonlight

For debug, uncomment the line 11 of Moonlight.sh

---

This is a temporary bypass to get Moonlight working from beta8. The best way to handle IP/pair/map steps should be integrating them to the UI.

**Pull request closed without merging**
