### PR TITLE
xu4: update the xpad driver to the last kernel one.

### PR DESCRIPTION
**Pull request by nadenislamarre**
fixes the xu4 build. (driver compiled but not tested, i've no xbox pad)

Signed-off-by: Nicolas Adenis-Lamarre nicolas.adenis.lamarre@gmail.com

### CODE REVIEW

**Comment by grgohr** [comment]
hello @nadenislamarre , does that fix include the [Xinmo patch](http://ithink.ch/blog/2013/09/08/patching_the_linux_kernel_to_install_the_xin-mo_dual_arcade_driver_on_a_raspberry_pi.html) ? related to issue [#1036](https://github.com/recalbox/recalbox-os/issues/1036)
any fresh build soon on your lovely repo [http://recalbox.remix.free.fr/](http://recalbox.remix.free.fr/) ?
thanks

**Comment by nadenislamarre** [comment]
xu4 nightly build should arrive here soon, with automatic updates

http://archive.recalbox.com/4.1/

**Comment by grgohr** [comment]
thanks. is there an automated way similar to Win32DiskImage/img.gz to deploy such updates (boot/root.tar.gz) or the only way is the one described here [recalbox development basics](https://github.com/recalbox/recalbox-os/wiki/Recalbox-development---basics-%28EN%29) ?

**Comment by nadenislamarre** [comment]
you can download root and boot .tar.xz and put them into system/upgrade and reboot.

**Comment by grgohr** [comment]
thanks, the upgrade screen appears on reboot, but goes back to recalbox too fast with the following upgrade.err.log in the folder: cp: can't stat 'cmdline.txt': No such file or directory
any idea ?

**Comment by nadenislamarre** [comment]
an old bug.
create an empty file named cmdline.txt on the boot partition

**Comment by grgohr** [comment]
great, same bug/fix with config.txt, upgrade works fine then, thanks !

the xinmo controller still doesn't work as expected (1 player detected only, bug with old linux kernel)

when I compare the kernel patches from [xu4 ](https://github.com/recalbox/recalbox-buildroot/tree/e142402c7e5ed2b4c5e5567fa5423f94fca800c9/board/recalbox/kernel_patches_odroidxu4)with [4.4](https://github.com/recalbox/recalbox-buildroot/tree/e142402c7e5ed2b4c5e5567fa5423f94fca800c9/board/recalbox/kernel_patches_4.4) it seems that both Xinmo patches are missing, is it on purpose ?

**Comment by substring** [comment]
The xinmo works with usb_quirks. The required config should be in the _darn old_ xu4 kernel. But you need to add the quirks as kernel parameter. One way around was to make usbhid a kernel module and list all quirks in a usbhid.conf, as i mentionned earlier.

@nadenislamarre have you checked the xu4 buildroot fragment file to set usbhid as a module + imported the usbhid.conf from the pi build ?

**Comment by nadenislamarre** [comment]
@subs i don't remember precisely what i did. i don't really understand what
you mean, so i would say no.

**Comment by grgohr** [comment]
@substring @nadenislamarre I confirm that /etc/modprobe.d/usbhid.conf exists
but no quirks inside for xinmo
adding "options usbhid quirks=0x16c0:0x05e1:0x040" to it does not change a thing

should not add
`{ USB_VENDOR_ID_XIN_MO, USB_DEVICE_ID_XIN_MO_DUAL_ARCADE, HID_QUIRK_NOGET | HID_QUIRK_MULTI_INPUT },`
 to [board/recalbox/kernel_patches_odroidxu4/linux-4NES4SNES-hid-quircks.patch](https://github.com/recalbox/recalbox-buildroot/blob/rb-4.1.X/board/recalbox/kernel_patches_odroidxu4/linux-4NES4SNES-hid-quircks.patch) ?

**Comment by substring** [comment]
@grgohr do a lsmod, and tell me if you notice usbhid among the list

**Comment by grgohr** [comment]
@substring mmh nope, you're right it is missing

#lsmod
Module                  Size  Used by    Not tainted
hidp                   12332  2
bnep                    9719  2
bluetooth             208036 12 hidp,bnep
rfkill                  9968  2 bluetooth
8021q                  20407  0
garp                    4716  1 8021q
stp                     1533  1 garp
mrp                     5888  1 8021q
llc                     3457  2 garp,stp
uinput                  6564  0
xt_connmark             1477  2
iptable_nat             2281  0
nf_conntrack_ipv4      12667  3
nf_defrag_ipv4           960  1 nf_conntrack_ipv4
nf_nat_ipv4             3302  1 iptable_nat
nf_nat                 12634  2 iptable_nat,nf_nat_ipv4
nf_conntrack           67715  5 xt_connmark,iptable_nat,nf_conntrack_ipv4,nf_nat              _ipv4,nf_nat
iptable_mangle          1224  1
cdc_ether               3885  0
usbnet                 17873  1 cdc_ether
r8152                  50529  0
ads7846                11123  0
spidev                  5252  0
ina231_sensor           7961  0
spi_s3c64xx            13844  0
i2c_s3c2410             8819  0
joydev                  8560  0
#

**Comment by substring** [comment]
@grgohr can you `cat /etc/modprobe.d/usbhid.conf` ? or wherever usbhid.conf is, I don't have a full XU4 build at hand, need to confirm something before pushing a commit

**Comment by grgohr** [comment]
@substring yes :

#cat /etc/modprobe.d/usbhid.conf
#Juyao
options usbhid quirks=0x0314:0x0326:0x0040
options usbhid quirks=0x0314:0x0328:0x0040

#4NES4SNES
#options usbhid quirks=0x1781:0x0A9D:0x040

#Retrolink SNES
options usbhid quirks=0x1292:0x5346:0x040
options usbhid quirks=0x1292:0x5366:0x040

#retrobit Atari to USB Driver
options usbhid quirks=0x1292:0x4154:0x040

#Retrode
options usbhid quirks=0x0403:0x97c1:0x040

#HuiJia  USB GamePad Mayflash Sega Saturn
options usbhid quirks=0x0e8f:0x3010:0x040

#HuiJia  USB GamePad Mayflash NES SNES
options usbhid quirks=0x0079:0x1804:0x040

**Comment by substring** [comment]
Try to add a kernel parameter as said on http://forum.odroid.com/viewtopic.php?f=95&t=18729#p123941

the parameter is usbhid.quirks=0x16c0:0x05e1:0x040

as it implies some risky editing, tell me if you prefer not being the guinea pig. We can manage in another way in a few days eventually

**Comment by grgohr** [comment]
yes, thanks I already tried editing boot.ini yesterday while checking other threads and that works great solves the player2 issue for xinmo (not afraid of risky editing :) )

`setenv console "console=ttySAC2,115200n8 usbhid.quirks=0x16c0:0x05e1:0x040"`
`setenv bootargs "${bootrootfs} ${console}"`

but it would probably be better to have to proper build including it without hacking the boot.ini
also I don't know if the controller not working in Moonlight is related to that issue

**Comment by substring** [comment]
If the boot.ini editing works, i will add it in the build. But might just also be a kernel.patch that is not included in thay kernel version

**Pull request merged**
