### PR TITLE
Rb 4.1.x nadenislamarre libretro glupen64

### PR DESCRIPTION
**Pull request by nadenislamarre**
make it compile for x86 x86_64 odroids c2 and xu4

note1 : x86 compilation is not tested while i've no space to keep all the archs on my computer.
note2 : compile doesn't mean it works. but i really trust it will. testers are welcome.

### CODE REVIEW

**Comment by paradadf** [comment]
It would be good to have the same button mapping as mupen64plus.

**Comment by nadenislamarre** [comment]
is it different ? did you do a test ?

**Comment by rockaddicted** [comment]
yes it is different.

-mupen standalone version : 

| N64 pad | ES pad (snes) |
| :-: | :-: |
| A | B |
| B | Y |

-mupen libretro version (glupen64) : 

| N64 pad | ES pad (snes) |
| :-: | :-: |
| A | A |
| B | B |

**Comment by digitalLumberjack** [comment]
Open an issue for the mapping if necessary.

**Pull request merged**
