### PR TITLE
Buildroot: Rewrite post-image scripts.

### PR DESCRIPTION
**Pull request by pasnox**
Allow to use them from in source tree and out of source tree.
Also shrink the code to make it more readable.
Add support for own ssh key and sftp-server.
Fix boot and share .tar.xz permissions.

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
@pasnox why not enable the sftp in buildroot ?

**Comment by pasnox** [comment]
Dropbear does not comes with a sftp-server implementation - only openssh does.
We prefer Dropbear over openssh for lightweight memory footprint.
We can't install both dropbear and openssh at the same time from buildroot, so I need to build the sft-server on my own here and copy it.
It's only done when in 'dev' mode  - when u use a recalbox ssh key to avoid builds for standards release.

**Comment by digitalLumberjack** [comment]
Sorry pal i don't like to have this in the production script for building target. Maybe we could create a package for the sftp server

**Comment by pasnox** [comment]
Ok, I will update the merge request to change that.

**Comment by pasnox** [comment]
Just rebased my changes after having removed ssh / sftp.
I still let the authorized_keys permissions fix because it's needed to avoid troubles, but no more ssh key is inserted.

**Comment by digitalLumberjack** [comment]
Vendu !

**Pull request merged**
