### PR TITLE
Update libretro-fba.mk

### PR DESCRIPTION
**Pull request by barbudreadmon**
Please make sure your PR is ready to be merged !
- [ ] You added the changes in CHANGELOG.md
- [ ] You choose the right repository branch to make the PR
- [ ] You described the PR as below

Fixes #XXXX
## 
- 

Related to (put here the others PR in other repositories)

Removed useless profile="performance" (I ditched this a few months ago)
Removed useless platform setting (it's just a shortcut for people who don't know how to setup cflags)
Bumped to v0.2.97.39 with latest fixes for irem and the speedhack for psikyo/suprnova.

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
Can one of the admins verify this patch?

**Comment by substring** [comment]
@digitalLumberjack are you testing auto-reply ? lol 
See https://forum.recalbox.com/topic/4454/fba-new-core-option/

**Comment by digitalLumberjack** [comment]
build board rpi3

**Comment by digitalLumberjack** [comment]
@substring Can one of the admins verify this patch? was an automatic message.

I should use a jenkins user for that :)

The build board rpi3 is the command to build the current pr for rpi3

**Pull request merged**
