### PR TITLE
Add firmwares

### PR DESCRIPTION
**Pull request by Laddyacris**
Please make sure your PR is ready to be merged !
- [X] You added the changes in CHANGELOG.md
- [X] You choose the right repository branch to make the PR
- [X] You described the PR as below

Fixes #155 #1046 #1049

Changes :
- /lib/firmware/brcm/BCM20702A1-0b05-17cb.hcd

### CODE REVIEW

**Comment by nadenislamarre** [comment]
be carefull.
you should recheck this pr.
buildroot already includes these firmwares (at least some), but while buildroot have added them, we've not checked the boxes into buildroot.
The file  ath3k-1.fw is for example in my x86 build.

**Comment by substring** [comment]
unless you have a list of the firmwares included in #472 it's a little hard to know which is available or not

**Comment by nadenislamarre** [comment]
ls on your usb key ;-)

**Comment by substring** [comment]
I just checked on the X86-alpha4 : none of the 2 fw are included

**Comment by nadenislamarre** [comment]
normal. it was added in the last alpha.
I saw it when i added the ati firmwares.

**Comment by substring** [comment]
and how can we sort out what's necessary on x86 or on smaller boards ?
`/lib/firmware` is 413MB on my alpha4, we can't afford such space on pi/odroid (33MB as of 4.1 for now)

**Comment by nadenislamarre** [comment]
buildroot description and google
type make config , buildroot put wifi together etc

**Comment by nadenislamarre** [comment]
@substring /lib/firmware is 60MB on my key. about 7MB for the ati that are not on the rpi.

**Pull request merged**
