### PR TITLE
linapple-pie (Apple ][ Emulator) : Fix recalbox/recalbox-os#523

### PR DESCRIPTION
**Pull request by LaurentMarchelli**
Hi, here we are, linapple-pie added, great thank's to @lmerckx for the patch and to @substring to have forwarded the information.
- Theme done for simplelight with the Utima V Music theme.
- Worked and tested on rpi2.
- Working out of the box without any configgen.
- Works with standard usb joystick, some troubles on button configuration with PS3 sinasix joystick that should be solved with configgen.
- Configgen is on going for fine tuning the emulator.
- Not very pleased with the S12populateshare patch as it is package dependent, but for the moment it does the job.

Fix recalbox/recalbox-os#523

### CODE REVIEW

**Comment by substring** [comment]
Congratz dude ! That's some great job ^^

**Comment by LaurentMarchelli** [comment]
Thank's, I really appreciate, I really owed u that for the great project Recalbox is. ;-)

**Comment by digitalLumberjack** [comment]
really nice, let's try that :)

**Comment by LaurentMarchelli** [comment]
Karateka is a nice try, using your joystick you may have to change the value of Joy0Button1 and     Joy0Button2 in ~/.linapple/linapple.conf with the SDL needed value. 
For instance 0 and 1 are not a good choice for PS3.
But ... linappleGenerator is coming soon ... 
I still have some issues on how to run the complete test on ubuntu ... 
I guess recalboxFiles.py is not the smartest implementation for tests overrides. :-)

**Comment by digitalLumberjack** [comment]
You're right :(

**Pull request merged**
