### PR TITLE
Rb 4.1.x nadenislamarre Network: add connman, a network manager

### PR DESCRIPTION
**Pull request by nadenislamarre**
Please make sure your PR is ready to be merged !
- [x] You added the changes in CHANGELOG.md
- [x] You choose the right repository branch to make the PR
- [x] You described the PR as below
  - automatic dhcp on ethernet wire connection
  - switch automatically on wifi if wifi is available and ethernet wire is removed
  - multiple wifi configurations connections in recalbox.conf (special chars on the wifi password have to be tested)
  - wifi open/wep/wpa/wpa2 connections (require tests)
  - wifi autoscan every 5 minutes if no network is available
  - no more eth0/eth1/wlan0/wlan1 hack
  - recalbox-config.sh wifi list to list wifi (require wifi enabled before)
  - custom configuration available via /recalbox/share/system/network-connman.config (static ip / vpn)
  
  Signed-off-by: Nicolas Adenis-Lamarre nicolas.adenis.lamarre@gmail.com

Related to (put here the others PR in other repositories)

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
Seem great nicolas. I'll review that soon :)

**Comment by nadenislamarre** [comment]
of course it's great !
I use it on my 4.0 sd card, no more need to reboot my recalbox because my internet box starts after the rpi.
Do you plan a 4.1 nightly build to make more tests from a clean install ?
I need to test migraion from 4.0 to 4.1 too because i replaced a link by a file which is not supported by the current upgrade system (perhaps a tar option to find to force it).

**Comment by digitalLumberjack** [comment]
Good job pal.

**Comment by pasnox** [comment]
Does not works with 4.1.x and rpi1

**Comment by nadenislamarre** [comment]
can you explain ?

**Comment by pasnox** [comment]
not related to this PR: network does not works also before this PR.

**Pull request merged**
