### PR TITLE
 Bump fba_libretro to the latest commit

### PR DESCRIPTION
**Pull request by paradadf**
Please make sure your PR is ready to be merged !
- [ ] You added the changes in CHANGELOG.md
- [x] You choose the right repository branch to make the PR
- [x] You described the PR as below

Fixes #XXXX

Changes :
- Fixes crash on some games like Wonderboy (wboy.zip), probably some irem and macross issues as well

Related to (put here the others PR in other repositories)
https://github.com/libretro/fbalpha/commit/cd04ce06635c46146863c1f718ffe2c2c56a3ea2

### CODE REVIEW

**Review by substring — COMMENTED** [review]
Maybe we should first handle the right platform for pi3 ? see https://github.com/libretro/fbalpha/blob/master/makefile.libretro#L205

The whole makefile needs a little tweaking

**Comment by substring** [comment]
not makefile, but package sorry

**Comment by paradadf** [comment]
That is way out of my league bro, sorry. Should I close this?

**Comment by substring** [comment]
no don't, i'll think about it once this PR is merged :)

**Comment by digitalLumberjack** [comment]
Are we still in the same version of the roms ?

**Comment by paradadf** [comment]
no quite... it changed from 0.2.97.3**7** to 0.2.97.3**8**. But 0.2.97.38 works with the current beta as well.

**Comment by digitalLumberjack** [comment]
Alright, the 4.1 is not even in beta, let's merge

**Pull request merged**
