### PR TITLE
PPSSPP : clone the right version, not the current one

### PR DESCRIPTION
**Pull request by substring**
Please make sure your PR is ready to be merged !
- [ ] You added the changes in CHANGELOG.md
- [x] You choose the right repository branch to make the PR
- [x] You described the PR as below

Fixes #XXXX

Changes :
- the PPSSPP_VERSION was useless until now
- forced ARMv7 specific flags

Related to (put here the others PR in other repositories)

### CODE REVIEW

**Comment by nadenislamarre** [comment]
you should distinguish xu4 and mali sdk. for example the c2 is mali sdk and arm8
use the same as you did for rpi3

**Comment by substring** [comment]
Are there any C2 vars yet ?
And ppsspp has no armv8 switch for now, otherwise it would be enabled for pi3 too :)

**Comment by nadenislamarre** [comment]
i just say instead of :
if mali set arm7
be replaced by
if xu4 set arm7
as you did for rpi3

**Comment by substring** [comment]
@nadenislamarre does it look better now ?

**Comment by nadenislamarre** [comment]
yes, thanks.

**Comment by digitalLumberjack** [comment]
thank to both of you

**Pull request merged**
