### PR TITLE
add support for usb network interfaces

### PR DESCRIPTION
**Pull request by damiencourousse**
Everything is in the title.  I would like to get a network access via a USB network interface, so that I can share the network connection of my smartphone with the recalbox box.

This change allows usb network interfaces to be ifuped at startup.  

I am not that much familiar with buildroot, and maybe there is a better way to do this.  For example, it would be nice to be able to mount usb network interfaces after startup.  Kodi currently supports this, but I am not sure how to achieve this in recalbox.  I would happy to add more changes to support this: tips are welcome !!

thanks,
Damien

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
Hi pal, thanks for your pr.
We are about to release 4.0, i cannot merge new feature in it. Maybe you could reopen a PR on 4.1 branch and close this one, and we could discuss about the code on the new pr ?

Thanks :)

**Comment by damiencourousse** [comment]
hello,

Yes, I can open a new PR on 4.1.  But I would like to ask you for an advice before: in 4.1, `eth0` has disappeared from `/etc/network/interfaces`, and I see that the script `recalbox-config.sh` no longer takes the command `ethernet`.  How is the ethernet interface auto-mounted?  Would this be suitable for usb network interfaces as well?

thanks,
Damien

**Comment by substring** [comment]
It's handled by connman on 4.1. Maybe @nadenislamarre can give more details

**Comment by damiencourousse** [comment]
I will have a look, thanks.

**Comment by damiencourousse** [comment]
Closing.  Thanks for your feedback!

It looks like my feature request will be supported by connman in the next release.  Currently, in version 4.0-beta3, networking via usb ethernet is already supported by the Linux kernel, but the network connection is not automatically mounted.

thanks,

**Comment by nadenislamarre** [comment]
dont close.
as far as i remember i have enabled only some connmann feature. i have to
check the good one is enabled

Le dimanche 29 mai 2016, damiencourousse notifications@github.com a
écrit :

**Comment by nadenislamarre** [comment]
connman modules enabled :
Ethernet support
WiFi support
command line client

disabled:
WISPr support
Bluetooth support
loopback support
neard support
ofono support

do you known which module is required for what you want ?

**Comment by damiencourousse** [comment]
hello Nicolas,

The ethernet module should be enough for my needs.
I had a look around on the internet but could not find better information for this, sorry.  

best regards,
Damien

**Pull request closed without merging**
