### PR TITLE
Enable highscores for fba_libretro

### PR DESCRIPTION
**Pull request by paradadf**
Please make sure your PR is ready to be merged !

- [x] You added the changes in CHANGELOG.md
- [x] You choose the right repository branch to make the PR
- [x] You described the PR as below

Fixes #XXXX

Changes :
- Place hiscore.dat from http://highscore.mameworld.info/download.htm (use 'old format hiscore.dat (pre mame v0174)' version) in SAVE_DIRECTORY

Related to (put here the others PR in other repositories)

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
Can one of the admins verify this patch?

**Comment by substring** [comment]
may i suggest we don't bump 3 times a week ? :) Anyway we'll have to do a major bump sooner or later for all emulators. Let this one be the last before some time :grin:

**Comment by paradadf** [comment]
Ok sorry, I was just doing that to have the latest version for the compatibility list.

**Comment by rockaddicted** [comment]
Thanks dude. Can you please update these files too ? (*.dat files,
_readme.txt with highscore  info, etc...)
https://github.com/recalbox/recalbox-buildroot/tree/rb-4.1.X/board/recalbox/fsoverlay/recalbox/share_init/roms/fba_libretro

**Comment by paradadf** [comment]
I hope it is correct now.
I don't have the new FBA_libretro_NEOGEO_only.dat nor fba_libretro_gamelist.txt

**Comment by rockaddicted** [comment]
Great thank you !
Maybe @Laddyacris have these files (FBA_libretro_NEOGEO_only.dat / fba_libretro_gamelist.txt) ?

**Comment by Laddyacris** [comment]
No, I have not the new dat file , @Nachtgarm can you create new dat file ?

**Comment by ghost** [comment]
Sure thing, @Laddyacris 
Here you go: https://www.dropbox.com/s/s8xtfcspfg6bapy/FBA_0.2.97.39.zip?dl=0

As always, it includes
1. Complete DAT | `FB Alpha v0.2.97.39.dat`
2. NeoGeo Parents Only | `FBA_NEOGEO_parents_only.dat`
3. NeoGeo only (including NeoGeo Clones) | `FBA_NEOGEO_only.dat`
4. Parents only (without NeoGeo) | `FBA_parents_only.dat`

**Comment by paradadf** [comment]
Thanks @Nachtgarm!

Should I create a "clrmamepro" folder and put all the dats inside like in mame?

**Comment by paradadf** [comment]
Done! I did to have it more organized.
The only thing left is a new fba_libretro_gamelist.txt, but no idea where to find it.

**Comment by paradadf** [comment]
Found it! Now everything should be fine :)

**Comment by rockaddicted** [comment]
perfect ;)

**Comment by paradadf** [comment]
I'm not sure anymore where exactly the samples directory and highscore.dat should go. Can you please tell me? https://github.com/libretro/fbalpha/blob/da57ff8fe137cea24bd23c7290591fecc9a6d778/README.md

Right now, I put them into
/recalbox/share/roms/fba_libretro/samples/
/recalbox/share/roms/fba_libretro/highscore.dat

but I'm not sure if highscore.dat should go into saves and the samples aren't working for me there :S

UPDATE: I found it! the right place (SYSTEM_DIRECTORY) is
/recalbox/share/bios/fba/samples/
and I'll assume that the SAVE_DIRECTORY is
/recalbox/share/saves/fba_libretro/highscore.dat

**Comment by rockaddicted** [comment]
Yep indeed `SYSTEM_DIRECTORY` = `/recalbox/share/bios` and `SAVE_DIRECTORY` = `/recalbox/share/save`

**Comment by paradadf** [comment]
Ok, thanks for the confirmation. I'll make a new PR with everything in the right place and close this one.
I saw something that is beyond my skills about the S12populateshare to recreate the folders if the user erases them. 
https://github.com/recalbox/recalbox-buildroot/pull/430/commits/3b5dfa932b872b2176548e1c78a7d8a8b36fa458

**Pull request closed without merging**
