### PR TITLE
Update 8bitdo FC30 Joystick Bluetooth

### PR DESCRIPTION
**Pull request by neolao**
**Warning /!\**
The firmware 1.41 does not work.
I switched to 1.40 to map the gamepad.

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
Can you check if the firmware change the name of the controller when you try to syncrhonise the bluetooth ? (double check spaces etc)

**Comment by neolao** [comment]
It's a weird behavior. The pairing can generate a joystick named like a PS3 controller. Here is the output of SDL :

```
$ /usr/recalbox-api/libs/bin/joysticks-linux-arm
```

```
Joystick 1 :
- JoyID = 1
- GUID = 060000004c0500006802000000010000
- Name = PLAYSTATION(R)3 Controller (64:03:D8:98:7F:06)
- Device path = /dev/input/js1
```

I think the firmware 1.41 (http://8bitdo.com/fc30joystick/Firmware.html) try to simulate a PS3 Controller by default.

When I try to map buttons, I lost connection after the first button.

**Comment by digitalLumberjack** [comment]
Ra. Even with Start + R ?

**Comment by neolao** [comment]
Ok it works now with the firmware 1.41, simply with `HOME`. I don't know why I was stuck on the PS3 mode.

**Pull request merged**
