### PR TITLE
Rb 4.1.x firmwarebumped v2

### PR DESCRIPTION
**Pull request by ian57**
Please make sure your PR is ready to be merged !

- [x] You added the changes in CHANGELOG.md
- [x] You choose the right repository branch to make the PR
- [x] You described the PR as below

Fixes #XXXX
Bump to Bump rpi-userland 8e84b9003d8259472f9c79b385443b1b4975203e and rpi-firmware b365edad4e75126fb9bfee2325652758407e4f74 to change be able to change video résolution on the fly via the vcgencmd command. This will be very useful the get pixel perfect on rgb screen
Changes :
rpi-userland

- 8e84b9003d8259472f9c79b385443b1b4975203e package/rpi-userland: include TARGET_CFLAGS to the overloaded CFLAGS
 - 9cc1da8f5a03baf1f1c6fc791051cadeb19765da rpi-userland: bump version
 - c8cd2736372a923fb35804af096a5445e8e275e8 package/rpi-userland: bump version, add hash

rpi-firmware

- b365edad4e75126fb9bfee2325652758407e4f74 rpi-firmware: bump version
- 97e3d82d91fbb10f891ffa691bdd0e66cc1821d8 rpi-firmware: remove empty host dependencies definition
 - 416fd9cd13ae4fbad0d4499ca2ce90447603a4e1 Replace (e)glibc by glibc
 - 55768aff2ef7437248e91c351c3ea6f650a28584 package/rpi-firmware: bump version, add hash
- fedfc08b2b4ab9ed4dc9b385a0928e8fa967ae8f package/rpi-firmware: bump version for rpi0

Related to (put here the others PR in other repositories)
https://github.com/buildroot/buildroot/commits/master/package/rpi-firmware 
https://github.com/buildroot/buildroot/commits/master/package/rpi-userland

### CODE REVIEW

**Comment by ian57** [comment]
Need to check if it works before PR!

**Comment by ian57** [comment]
Reopen after tests

**Comment by digitalLumberjack** [comment]
@substring can you test that please

**Comment by digitalLumberjack** [comment]
build on rpi3

**Comment by digitalLumberjack** [comment]
build board rpi3

**Comment by substring** [comment]
@digitalLumberjack LGTM. This gives many options yet to explore :)

**Comment by digitalLumberjack** [comment]
build board rpi3

**Comment by digitalLumberjack** [comment]
@ian57 can you merge rb-4.1.X on this branch please (that will fix the kodi youtube plugin build)

**Comment by substring** [comment]
build board rpi3

**Comment by ian57** [comment]
@digitalLumberjack done it this morning.

**Pull request merged**
