### PR TITLE
Update moonlight-embedded.mk

### PR DESCRIPTION
**Pull request by substring**
Please make sure your PR is ready to be merged !
- [ ] You added the changes in CHANGELOG.md
- [x] You choose the right repository branch to make the PR
- [x] You described the PR as below

Fixes https://github.com/recalbox/recalbox-os/issues/1080

Changes :
- updates moonlight to 2.2.2

Related to (put here the others PR in other repositories)

Required for GFE 3.0.7

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
On 4.0 ? Does it fix any know bug ?

**Comment by substring** [comment]
GFE 3.0.7 is out, users will update. This one requires moonlight 2.2.2.

Or they can wait for the first beta of 4.1, which has no eta.

The recalbox release cycle can't match nvidia's gamestream protocol updates.

**Comment by digitalLumberjack** [comment]
Ok if you tested it i can merge on 4.0

**Comment by Phil5004** [comment]
How can I update moonlight in the Recalbox build?

**Comment by substring** [comment]
Switch to the unstable branch

**Comment by Phil5004** [comment]
Got a link to the unstable versions, just unzip everything?

**Comment by substring** [comment]
Read your recalbox.conf

**Comment by Phil5004** [comment]
http://archive.recalbox.com/4/rpi3/unstable/recalbox-unstable-build-21/
Am I right here for the unstable versions of recalbox to install them?

**Pull request merged**
