### PR TITLE
bumped retroarch + corrected config/readme files

### PR DESCRIPTION
**Pull request by rockaddicted**
Please make sure your PR is ready to be merged !
- [x] You added the changes in CHANGELOG.md
- [x] You choose the right repository branch to make the PR
- [x] You described the PR as below

Fixes #XXXX

Changes :
- bumped retroarch to v1.3.4
- updated es_inputs.cfg
- corrected some config/readme files

Related to (put here the others PR in other repositories)

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
@rockaddicted i wonder if it's a good idea to change the retroarch version just before the release. What are the changes ?

**Comment by rockaddicted** [comment]
Yes I know, I don't like too to bump version just before stable release.
But I'm using this version since one month one my 4.1 and don't have notables problems.
This one fix some problems about remap games option and retroachievements.

**Comment by substring** [comment]
same as rock : been using it for over a month, works pretty fine

**Comment by digitalLumberjack** [comment]
Cool :)

**Pull request merged**
