### PR TITLE
Set gpu_mem_1024=256 (RPi2 & RPi3)

### PR DESCRIPTION
**Pull request by paradadf**
Please make sure your PR is ready to be merged !

- [ ] You added the changes in CHANGELOG.md
- [x] You choose the right repository branch to make the PR
- [x] You described the PR as below

Fixes #XXXX

Changes :
- Allocate less memory to the gpu to have more ram available.
Fixes problems with fba games with samples (fireshrk, ghox, vimana) not launching at all because of memory constraints.
EmulationStation using the official recalbox themes doesn't need so much gpu as before. This has been tested with 43 available systems without problems.
- I have tested n64 games and couldn't notice any performance drawback with this change.

Related to (put here the others PR in other repositories)

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
Can one of the admins verify this patch?

**Comment by digitalLumberjack** [comment]
Did you check with dreamcast and ppsspp ?

**Comment by paradadf** [comment]
I can't test those because I only have a RPi2.

**Comment by digitalLumberjack** [comment]
okay we will test before merging :)

**Comment by digitalLumberjack** [comment]
The second issue i think about is for emulationstation themes that uses png for background. 512mo was able to store ~25 background images not more. So we have to refactor es or this PR will break many recalboxes :)

**Pull request closed without merging**
