### PR TITLE
pm2 daemon should be started in the API directory

### PR DESCRIPTION
**Pull request by neolao**

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
Isn't it dangerous to change the current directory in a init.d script (just asking i don't think it is)

**Comment by neolao** [comment]
I will try to find another way to run the command.

**Comment by neolao** [comment]
Ok I found something. I set the environment variable API_HOME in the script.
The last release of the API uses it.

**Comment by digitalLumberjack** [comment]
Thank you :) That is the best solution. I checked and i saw that cd is ok in init.d scripts as each script is started in a new bash (that seems normal :)

**Pull request merged**
