### PR TITLE
Bumped libretro cores

### PR DESCRIPTION
**Pull request by rockaddicted**
Please make sure your PR is ready to be merged !

- [x] You added the changes in CHANGELOG.md
- [x] You choose the right repository branch to make the PR
- [x] You described the PR as below

Fixes https://github.com/recalbox/recalbox-os/issues/1081

Changes :
- Bumped libretro cores on lastest version - Based on @paradadf PR https://github.com/recalbox/recalbox-buildroot/pull/614
- Missing cores : 
    - bluemsx - will be done on a next PR
    - mupen64plus - didn't use for the moment, will be bumped later

### CODE REVIEW

**Comment by rockaddicted** [comment]
@digitalLumberjack Tested all cores on rpi3, everything is ok.
Can be merged.

**Review by digitalLumberjack — APPROVED** [review]
Great i'll merge when ci is back

**Comment by digitalLumberjack** [comment]
@rockaddicted you can remove WIP from the title

**Comment by rockaddicted** [comment]
@digitalLumberjack done

**Pull request merged**
