### PR TITLE
Fix megatools prefix

### PR DESCRIPTION
**Pull request by pasnox**
Please make sure your PR is ready to be merged !
- [] You added the changes in CHANGELOG.md
- [x] You choose the right repository branch to make the PR
- [x] You described the PR as below

Changes :
- Fix megatools prefix

### CODE REVIEW

**Comment by rockaddicted** [comment]
Haha thanks dude

**Comment by pasnox** [comment]
don't merge yet - it's buggy

**Comment by digitalLumberjack** [comment]
What is buggy ?

**Comment by pasnox** [comment]
the config.in indentation is wrong and cause package build failing

**Comment by pasnox** [comment]
Ready to be merged.

**Comment by digitalLumberjack** [comment]
thx

**Pull request merged**
