### PR TITLE
Update recalbox-support.sh

### PR DESCRIPTION
**Pull request by Laddyacris**
Please make sure your PR is ready to be merged !
- [x] You added the changes in CHANGELOG.md
- [x] You choose the right repository branch to make the PR
- [x] You described the PR as below

Fixes #XXXX

Changes :
- Add es_input.cfg

Related to (put here the others PR in other repositories)

### CODE REVIEW

**Comment by rockaddicted** [comment]
Bip bip :tada:

**Comment by MikaXII** [comment]
Hourraaaaaaaa!

**Comment by substring** [comment]
W000000t

**Comment by digitalLumberjack** [comment]
Wonderful!

**Comment by Laddyacris** [comment]
Merci les amis :D

**Pull request merged**
