### PR TITLE
[4.0] Delete 8bitdo Gamepads USB configuration

### PR DESCRIPTION
**Pull request by paradadf**
Please make sure your PR is ready to be merged !
- [ ] You added the changes in CHANGELOG.md
- [ ] You choose the right repository branch to make the PR
- [x] You described the PR as below

Fixes https://github.com/recalbox/recalbox-os/issues/1087

Changes :
- For 8bitdo gamepads to work over USB, the user will need to configure them through ES. The standard will be a Bluetooth connection, which remains. This avoids the conflict for the gamepad sending double signals when connected through USB, as the controller doesn't stop emitting when plugged in.

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
build board rpi3

**Comment by digitalLumberjack** [comment]
Can one of the admins verify this patch?

**Comment by digitalLumberjack** [comment]
build board rpi3 i said

**Comment by digitalLumberjack** [comment]
build board rpi3

**Comment by digitalLumberjack** [comment]
build board rpi3

**Comment by digitalLumberjack** [comment]
The issue is : when you have a recalbox and a 8bitdo, it was easy to plug it in usb and configure the bluetooth. Now it's not possible anymore, unless you reconfigure the pad...

**Comment by paradadf** [comment]
IMO, the most common thing when your pad is low on battery would be to plug it into the Pi and keep playing. That is currently not possible, as the Bluetooth of that pad will still be working. I doubt anyone wants to play with cable if the pad Supports Bluetooth, so the only thing they need is to pair it once. But if you consider the current behaviour better, just let me know and I won't insist anymore.

**Comment by digitalLumberjack** [comment]
@substring @rockaddicted any opinion ?

**Pull request closed without merging**
