### PR TITLE
Test auto build jenkins

### PR DESCRIPTION
**Pull request by digitalLumberjack**
Please make sure your PR is ready to be merged !
- [ ] You added the changes in CHANGELOG.md
- [ ] You choose the right repository branch to make the PR
- [ ] You described the PR as below

Fixes #XXXX
## 
- 

Related to (put here the others PR in other repositories)

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
Can one of the admins verify this patch?

**Comment by digitalLumberjack** [comment]
build board rpi3

**Comment by digitalLumberjack** [comment]
build board rpi3

**Comment by digitalLumberjack** [comment]
build board rpi3

**Comment by digitalLumberjack** [comment]
build board rpi3

**Comment by digitalLumberjack** [comment]
build yolo board yolo rpi3

**Comment by digitalLumberjack** [comment]
build board rpi3

**Comment by digitalLumberjack** [comment]
build yolo

**Comment by digitalLumberjack** [comment]
build board rpi2

**Comment by digitalLumberjack** [comment]
build board rpi2

**Comment by digitalLumberjack** [comment]
build board x86

**Comment by digitalLumberjack** [comment]
build board x86

**Comment by digitalLumberjack** [comment]
build board rpi1

**Comment by digitalLumberjack** [comment]
build board rpi1

**Comment by digitalLumberjack** [comment]
build board x86

**Comment by digitalLumberjack** [comment]
build board rpi1

**Comment by digitalLumberjack** [comment]
build board xu4

**Comment by digitalLumberjack** [comment]
build board odroid_xu4

**Comment by digitalLumberjack** [comment]
build board odroidxu4

**Comment by digitalLumberjack** [comment]
build board odroidxu4

**Comment by digitalLumberjack** [comment]
build board odroidxu4
should work with two lines

**Comment by nadenislamarre** [comment]
look like youve been hacked.

Le dimanche 23 octobre 2016, digitalLumberjack notifications@github.com a
écrit :

**Pull request closed without merging**
