### PR TITLE
First working commodore integration for rpi2 and recalbox

### PR DESCRIPTION
**Pull request by MICKtheBIG**
Please make sure your PR is ready to be merged !
- [ ] You added the changes in CHANGELOG.md
- [ ] You choose the right repository branch to make the PR
- [x] You described the PR as below

Fixes #452, #38, 

Changes :
- Added .mk file for vice 2.4.24
- Added a first vice config. (Should be improved)
- Added theme for commodore c64
- Added demo ROMs for c64

Related to (put here the others PR in other repositories)
- I a few minutes you get a PR for configgen

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
Thanks, why is it "for rpi2" ? Cannot it be run on rpi1 and 3 ?
Could you replay the PR on the 4.1.X branch ? This is the branch for new features, 4.0.X is stabilized right now :)
Could you add in CHANGELOG.md the changes you made ?

Thank you :)

**Comment by MICKtheBIG** [comment]
@digitalLumberjack: I only have a RPI2, so I could only test it on RPI2. I had to fight with some strange behavior of SDL... I should run on RPI1 and RPI3...

Yeah, I do a new PR for 4.1. branch and add a changelog.md but I won't manage before next week...

**Comment by digitalLumberjack** [comment]
Super :) Thank you :D

**Comment by digitalLumberjack** [comment]
I close :)

**Comment by picajoso** [comment]
I'm sorry, but I've just downloaded and installed Recalbox 4.0.0 beta 3 and I don't see C64 support - no folder to put the roms in. Could you explain how to enable that support?

**Comment by rockaddicted** [comment]
C64 support done on version 4.1.0, so be patient

**Comment by picajoso** [comment]
Fantastic, thanks for the update and the quick reply :) :+1:

**Comment by rockaddicted** [comment]
you are welcome

**Pull request closed without merging**
