### PR TITLE
Bump retroarch to last release due to integration of libretro-imagevi…

### PR DESCRIPTION
**Pull request by ian57**
Please make sure your PR is ready to be merged !
- [x] You added the changes in CHANGELOG.md
- [x] You choose the right repository branch to make the PR
- [x] You described the PR as below

Fixes # deletion of the libretro-imageviewer repository due to integration in retroarch cores. see https://github.com/libretro/RetroArch/tree/master/cores/libretro-imageviewer

Changes :
- bumped to 6690711ace3fe146d720d8755528bee8d8d87dd8 commit (25/07/2016)
- correction of the patch package/retroarch/retroarch-002-hotkey-select-fix.patch
- desactivation of the libretro-imageviewer package

Related to (put here the others PR in other repositories)

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
We will delete the package directory if everything is ok.

Thanks @ian57

**Comment by MikaXII** [comment]
We should keep old patch and put them in folder by versions. I mean folder `6690711ace3fe146d720d8755528bee8d8d87dd8` contain patch for this version, and folder `31bcb3d6f84b99c93844bde70251bcf3dec9ce7b`  new patch. this is no really important because it is used only by us but next time we should follow this practice

**Comment by substring** [comment]
Why ? You just have to check the history of a file ...

**Comment by MikaXII** [comment]
Best practice ^^.
`we should follow this practice` -> not an obligation

**Comment by substring** [comment]
@ian57 am I dreaming, or retroarch removed the imageviewer repo ?

**Comment by MikaXII** [comment]
@substring That why @ian57 has bumped retroarch's version.
They move imageviewer repo in Retroarch repo

**Comment by substring** [comment]
So it means the package is useless and doesn't compile anymore

**Comment by MikaXII** [comment]
Did you read this thread at the begining ? :D

**Pull request merged**
