### PR TITLE
Add helpers scripts.

### PR DESCRIPTION
**Pull request by pasnox**
install-ubuntu-deps.sh will install all needed dependencies on ubuntu.
build-br.sh will build buildroot for rpi1 by default or the given arch as first parameter.
mk-sdcard-img.sh will take a buildroot build images folder as first parameter
and generate a ready to dd sdcard img to be used on your rpi.
dd-sdcard-img.sh will dd a sdcard tar.xz img on your real sdcard.

### CODE REVIEW

**Comment by nadenislamarre** [comment]
Nice.
to be added : growfs.

**Comment by pasnox** [comment]
Hm not sure on how to use that - any hint / examples ?

**Comment by nadenislamarre** [comment]
when you run an openelec for the first time, commands are displayed on the
screen ;-)

**Comment by pasnox** [comment]
Hm i'm not using openelec, any chances u catched that ? :)

**Comment by nadenislamarre** [comment]
OK. i add it in my todo

**Comment by digitalLumberjack** [comment]
nice

**Pull request merged**
