### PR TITLE
retroarch hotkey fix

### PR DESCRIPTION
**Pull request by digitalLumberjack**
uses the @kivutar patch to correct hotkey on select coin on arcade cores.

### CODE REVIEW

**Comment by rockaddicted** [comment]
let's try this

**Comment by digitalLumberjack** [comment]
@nadenislamarre the udev file has been modified since the last commit, is it ok with the patch ?

**Comment by nadenislamarre** [comment]
sorry, i don't understand the question.
If it's about my retroarch patch for more allowed keys (same as sdl2), yes.

2015-12-17 20:03 GMT+01:00 digitalLumberjack notifications@github.com:

**Comment by digitalLumberjack** [comment]
Yes it was about that :) thanks

**Pull request merged**
