### PR TITLE
[4.0] Update 8bitdo NES30Pro

### PR DESCRIPTION
**Pull request by paradadf**
Please make sure your PR is ready to be merged !
- [ ] You added the changes in CHANGELOG.md
- [ ] You choose the right repository branch to make the PR
- [x] You described the PR as below

Fixes https://github.com/recalbox/recalbox-os/issues/1084

Changes :
- Some id and code values have changed, either with the latest firmware (v1.71) or even before. These are the latest working ones.

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
Can one of the admins verify this patch?

**Comment by paradadf** [comment]
4.0 is out... what about both PRs? No interest?

**Comment by digitalLumberjack** [comment]
Thanks paradadf

**Comment by digitalLumberjack** [comment]
As the 4.0 is stable for now, i won't merge it into 4.1. Could you recreate the pr for 4.1 please ?

**Comment by paradadf** [comment]
Of course.

**Pull request merged**
