### PR TITLE
SDL 1 patch

### PR DESCRIPTION
**Pull request by lmerckx**
Patch on SDL1 to avoid black screen with fbcon driver
(previously in dosbox PR but splitted for more convenience)

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
Thanks :) we will test that :)

**Comment by rockaddicted** [comment]
Happy to see you here @lmerckx 
Thanx

**Comment by LaurentMarchelli** [comment]
@lmerckx 
Thank's very much, you made my day. :-)

**Comment by substring** [comment]
HERE COMES A NEWWWWW CHALLENGER !!

Good job dude :)

**Pull request merged**
