### PR TITLE
OOB Remote control management.

### PR DESCRIPTION
**Pull request by LaurentMarchelli**
- Standard remote control can work OOB with xbmc as soon as they are referenced in the system's Lircmap.xml located in /usr/share/kodi/system/ (https://github.com/xbmc/xbmc/blob/master/system/Lircmap.xml).
- Corresponding LIRC conf files can be found at : http://lirc-remotes.sourceforge.net/remotes-table.html
- Sample made and tested with the mceusb (Media Center Edition)

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
@nadenislamarre is it ok ?

**Comment by nadenislamarre** [comment]
yes.

**Comment by nadenislamarre** [comment]
thanks a lot.

**Comment by digitalLumberjack** [comment]
Thanks Laurent :)

**Comment by LaurentMarchelli** [comment]
Others could be added if needed. 
You're welcome. :-)

**Pull request merged**
