### PR TITLE
dosbox: fix x86_64 compilation

### PR DESCRIPTION
**Pull request by nadenislamarre**
Existing patch :
Migrate dosbox to SDL2
See http://www.vogons.org/viewtopic.php?t=34770
Signed-off-by: Laurent Merckx <laurent-merckx@skynet.be>

Change :
=> I've put the sdl checks in configure.ac at the end of the file
while settings *FLAGS at the begining of the configure broke the basic configure steps (like checking char size returning 0 instead of 1 because of libSDL2*.so not found (i don't known why however while -L was specified, i've not found the deep deep cause)).
i've compiled rpi2, rpi3, c2, x86_64 to confirm it still compiles on all platforms.

Signed-off-by: Nicolas Adenis-Lamarre <nicolas.adenis.lamarre@gmail.com>

### CODE REVIEW

**Comment by ian57** [comment]
Yep, saw that with substring yesterday... We did not known why I had to install sdl2-dev on the host X86_64 computer to be able to compile the X86_64 recalbox dosbox . Thanks for the patch ;)

**Comment by nadenislamarre** [comment]
you dont need it anymore

Le jeu. 10 nov. 2016 à 05:59, Yann Morere notifications@github.com a
écrit :

**Comment by nadenislamarre** [comment]
on the configure.ac the line causing the pb is
cppflzgs=-L... -lSDL2 too soon which makes basic check to not compile as if
-L where not used

**Comment by nadenislamarre** [comment]
when it fails, grep libSDL congfig.log : libSDL.so file not found

**Comment by digitalLumberjack** [comment]
I can only trust you on this one :P

**Pull request merged**
