### PR TITLE
USBHID : compiled as a kernel modules for gamepad encoders

### PR DESCRIPTION
**Pull request by substring**
Please make sure your PR is ready to be merged !
- [x] You added the changes in CHANGELOG.md
- [x] You choose the right repository branch to make the PR
- [x] You described the PR as below

Fixes recalbox/recalbox-os#524 recalbox/recalbox-os#217 (not tested)

Changes :
- added /etc/modprobe.d/usbhif.conf for quirks
- USBHID is now a kernel module that can be configured with the above file
- gamepad encoders are now much more easy to configure when they require usb quirks

Related to (put here the others PR in other repositories)
N/A

**Needs USB general testing to check for no regression**

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
Are you sure the module auto load on boot ?

**Comment by substring** [comment]
Testers had it working OOtB, it's loaded on demand, the modules dependencies is built with the kernel

**Comment by digitalLumberjack** [comment]
could you put it in /etc/modules.conf to be sure ?

**Comment by substring** [comment]
YOLO MAN !
i pushed it to rb-4.1.x, up to you to decide

quite easy to rollback if things turn bad ...

**Pull request merged**
