### PR TITLE
Recalbox: Only build kodi packages when kodi is selected

### PR DESCRIPTION
**Pull request by LipkeGu**
Please make sure your PR is ready to be merged !

- [ ] You added the changes in CHANGELOG.md
- [X] You choose the right repository branch to make the PR
- [X] You described the PR as below

Fixes #XXXX

Changes :
- Do not compile KODI addons when KODI is not selected.

Description :
This PR fixed a bug where kodi addons gets selected when kodi isnt it.

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
Can one of the admins verify this patch?

**Comment by digitalLumberjack** [comment]
Hi nice job. That should be a buildroot (upstream) patch. We try to not modify kodi packages directly. And we always build kodi, or disable every kodi plugins when not enabling it.

**Comment by substring** [comment]
I just tested : disabling kodi in menuconfig blocks any sub-addon, so i'm surprised this does work. Maybe the .config wasn't updated consequently ?

**Comment by nadenislamarre** [comment]
these packages are added by me
and are not part of buildroot (too many language to add for buildroot)
it :
make the lang already available ( no download) for the end user
prevent to add kodi language files on the sdcard

the pr is good you can validate it.

**Comment by nadenislamarre** [comment]
note that i've done a script to autodetect new packages available on internet
https://github.com/nadenislamarre/batocera.linux/blob/rb-5.1.X-batocera.linux/scripts/linux/checkPackagesUpdates.sh

it's not finnished, but it works already for the kodi language packages:

$ ./scripts/linux/checkPackagesUpdates.sh
Groups: KODI RETROARCH OTHERS
+--------------------------------+------------------------------------------+------------------------------------------+
| Package                        | Available version                        | Version                                  |
+--------------------------------+------------------------------------------+------------------------------------------+
| dolphin-emu                    |                                          | 5.0                                      |
| kodi-resource-language-de_de   | 2.0.9                                    | 2.0.8                                    |
| kodi-resource-language-es_es   |                                          | 2.0.4                                    |
| kodi-resource-language-eu_es   |                                          | 2.0.0                                    |
| kodi-resource-language-fr_fr   |                                          | 2.0.10                                   |
| kodi-resource-language-it_it   |                                          | 2.0.5                                    |
| kodi-resource-language-pt_br   | 2.0.7                                    | 2.0.5                                    |
| kodi-resource-language-sv_se   | 2.0.7                                    | 2.0.5                                    |
| kodi-resource-language-tr_tr   | 2.0.7                                    | 2.0.6                                    |
| kodi-resource-language-zh_cn   |                                          | 2.0.3                                    |
| kodi-superrepo-repositories    |                                          | 0.7.04                                   |
| kodi-superrepo-repositories    |                                          | 0.7.04                                   |
| libretro-4do                   | fddde4cbeda9815ab53c056330c358345a89ac59 | c141664f13ecbcc4c4b91dd4d00d49b691d7d546 |
| libretro-81                    | 4b37e9d2cd2a9c9d7151f89db5d6d0c685874cab | 5e5dd8446db5f5ed3dc39a0cdd760f95b289aa40 |
| libretro-beetle-lynx           | 647656bb8c37ca35a287023cda0fcfed1f68fea4 | 54b9a6e8c88022098bfa6e3d47f48c119f1deb7a |
| libretro-beetle-ngp            | 626182666afd09d887a294332fa04693cc894703 | b24e145028727bace70148e844785debd73b8adb |
| libretro-beetle-pce            | 0c2f00b7754116f28547ade86b837dabbe43e541 | 3567dee8676bc4ea8b9720a3cf5cf652437361b6 |
| libretro-beetle-pcfx           | 045d89daae32fbd66e08ad61cad1beb6816227d4 | ac6387d16ed28f6b524a22ef3b8dd99284c3ed25 |
| libretro-pcsx                  | abaa8b9e916f689ba162a684c2e23890cea7d6da | bb22137d8a5b660777896b1c470d5fc906201b37 |
| libretro-snes9x-next           | 66ba1235df30d00e018866875bc6fa77643d5663 | dffda6f1e44522bd1e1465a49c42e407c0c3db5d |
| ppsspp                         |                                          | v1.3*                                    |
| retroarch                      |                                          | v1.3.6*                                  |
+--------------------------------+------------------------------------------+------------------------------------------+

**Comment by digitalLumberjack** [comment]
alright i merge :)

**Pull request merged**
