### PR TITLE
Rb 4.1.x nadenislamarre c2 ppsspp

### PR DESCRIPTION
**Pull request by nadenislamarre**
bump ppsspp version so that it supports aarch64.
it doesn't break configgen once subs has applied his configgen commit.

### CODE REVIEW

**Comment by substring** [comment]
@nadenislamarre you forgot the patch i sent you to update the path to gamecontrollerdb.txt

**Review by substring — CHANGES_REQUESTED** [review]
Need the following patch :

```
diff --git a/SDL/SDLJoystick.cpp b/SDL/SDLJoystick.cpp
index 1cde440..b19a381 100644
--- a/SDL/SDLJoystick.cpp
+++ b/SDL/SDLJoystick.cpp
@@ -21,7 +21,7 @@ SDLJoystick::SDLJoystick(bool init_SDL ): thread(NULL), running(true) {
        SDL_Init(SDL_INIT_JOYSTICK | SDL_INIT_VIDEO | SDL_INIT_GAMECONTROLLER);
    }

-   auto dbPath = File::GetExeDirectory() + "assets/gamecontrollerdb.txt";
+   std::string dbPath = "/recalbox/share/system/configs/ppsspp/gamecontrollerdb.txt";
    cout << "loading control pad mappings from " << dbPath << ": ";

    if (SDL_GameControllerAddMappingsFromFile(dbPath.c_str()) == -1) {
```

**Comment by ian57** [comment]
Hello the sdl patch seems to break the rpi3 compilation : 

```
>>> ppsspp 7ddd68de1798ac8ce5d626a1e05a910236c2ca5d Patching
....
Applying 004-SDL.patch using patch: 
patching file SDL/SDLJoystick.cpp
Hunk #1 FAILED at 21.
1 out of 1 hunk FAILED -- saving rejects to file SDL/SDLJoystick.cpp.rej
Patch failed!  Please fix 004-SDL.patch!
```

will put an eye on that

**Comment by substring** [comment]
Don't bother i'll do it. That's my patch but looks like some branches unsync'ed  when i wrote it and when all was pushed

**Comment by ian57** [comment]
No problem. Thanks

**Comment by ian57** [comment]
The patch was made twice : in 001-gamecontrollerdb_patch.patch and 004-SDL.patch. Simply remove the file 004-SDL.patch and it will work

**Pull request merged**
