### PR TITLE
Gamecon : update package to 1.2

### PR DESCRIPTION
**Pull request by substring**
Please make sure your PR is ready to be merged !
- [x] You added the changes in CHANGELOG.md
- [x] You choose the right repository branch to make the PR
- [x] You described the PR as below

Fixes https://github.com/recalbox/recalbox-os/issues/1057

Changes :
- update gamecon driver to 1.2

Related to (put here the others PR in other repositories)

Can't test it but it compiles fine ... Looks like a prYolo syndrom
Anyway, if it doesn't work, we can rollback it during the unstable phase

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
I don't have any controllers working. 
@recalbox/recalbox-testers anyone with a custom recalbox with original nes snes or psx controllers ?

**Comment by digitalLumberjack** [comment]
Still no one with controllers ?

**Comment by Didlith** [comment]
I have juste 
Xbox wireless controler
8bitdo nes30 pro
Ps3
So i have psx controler with usb adaptator
Do you want test this configuration ?

**Comment by moriceh** [comment]
If you want, I have 2 psx controllers plugged on GPIO's. But... can you give me the compiled version please ? ;)

**Comment by substring** [comment]
@moriceh what recalbox version do you have ?

**Comment by moriceh** [comment]
I have the latest unstable. Also, if you want I speak French ;)

**Comment by digitalLumberjack** [comment]
Can one of the admins verify this patch?

**Comment by digitalLumberjack** [comment]
build board rpi3

**Comment by moriceh** [comment]
I only have a pi 2 available...

**Comment by moriceh** [comment]
I have the latest unstable.

**Comment by substring** [comment]
@moriceh the PR is on the 4.1 branch, not the 4.0. So unless you have a 4.1, you can't test even if you're on the unstable branch. Maybe the best would be to wait that the 4.1 officially sits in the unstable update branch ?

**Comment by digitalLumberjack** [comment]
Let's test that live.

**Pull request merged**
