### PR TITLE
Add Vim to Recalbox

### PR DESCRIPTION
**Pull request by benutzer193**
Changes :
- add VIM

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
nice :)

**Comment by pasnox** [comment]
I would have preferred to see nano instead.
Vim is not friendly to standard users.

2016-04-06 12:10 GMT+02:00 digitalLumberjack notifications@github.com:

**Comment by substring** [comment]
Haha @pasnox
How long haven't you edited a file in recalbox ? Nano is included already :p

**Comment by pasnox** [comment]
Probably never yet :)

2016-04-06 19:41 GMT+02:00 Subs notifications@github.com:

**Pull request merged**
