### PR TITLE
Kodi : add sftp support

### PR DESCRIPTION
**Pull request by nadenislamarre**
Signed-off-by: Nicolas Adenis-Lamarre nicolas.adenis-lamarre@gmail.com

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
nice !

**Comment by dhobi** [comment]
Thx for this! Heading off to read more about buildroot. (At least I think I understand it now why sftp was not part of the protocol dropdown list).

**Comment by nadenislamarre** [comment]
i ve chechek kodi options. on ly one thing about pvr is not 3nabled. ( rhe
rzst of thz unactivated things are scrennsavers and such things)

**Comment by nadenislamarre** [comment]
Hum,

from the config.log,
still libusb is disabled, i must check what it is used for before. It could
be just normal.

configure:23771: result: == Wayland disabled. ==
configure:27984: result: == PulseAudio support disabled. ==
configure:28443: result: == X11 disabled. ==
configure:28475: == GOOM disabled. ==
configure:28482: == RSXS disabled. ==
configure:28638: == FishBMC disabled. ==
configure:28650: == ProjectM disabled. ==
configure:29438: == libusb disabled. ==
configure:29933: == Capabilities detection support disabled. ==
configure:30418: == VDPAU support manually disabled. ==
configure:30519: == VAAPI support manually disabled. ==
configure:30543: == VTBDecoder support manually disabled. ==
configure:30585: == OpenMax support manually disabled. ==

2015-12-31 7:28 GMT+01:00 Nicolas Adenis-Lamarre <
nicolas.adenis.lamarre@gmail.com>:

> i ve chechek kodi options. on ly one thing about pvr is not 3nabled. ( rhe
> rzst of thz unactivated things are scrennsavers and such things)

**Comment by dhobi** [comment]
http://forum.kodi.tv/showthread.php?tid=218851

"libusb is rather old and not needed if you have udev."

**Comment by nadenislamarre** [comment]
Thanks.

2015-12-31 10:35 GMT+01:00 Daniel Hobi notifications@github.com:

**Comment by dhobi** [comment]
Hmm I've just made a fresh install with http://archive2.recalbox.com/4.0.0/recalbox-4.0.0-nightly-build-51/
- Unfortunately, the sftp option is (still) not there. Did I try the wrong version or was the merge not included in this nightly build since it happened around midnight? Guessing wildly :-)

**Comment by substring** [comment]
build 51 has the PR#98 included in it, according to the build changes

**Comment by nadenislamarre** [comment]
can you send the config.log file from output/build/kodi-15xxxx please ?

2015-12-31 12:20 GMT+01:00 Subs notifications@github.com:

**Comment by substring** [comment]
that's something for @digitalLumberjack

**Comment by nadenislamarre** [comment]
why ?
my guess is just that the kodi directory has not been removed from
output/build before rebuilding
so, the configure doesn't include the sftp option.

2015-12-31 12:35 GMT+01:00 Subs notifications@github.com:

**Comment by nadenislamarre** [comment]
Ah, it's him who does the nightly build, not you. Ok.

2015-12-31 12:37 GMT+01:00 Nicolas Adenis-Lamarre <
nicolas.adenis.lamarre@gmail.com>:

**Comment by dhobi** [comment]
So, is the config.log still needed? :-)

**Comment by nadenislamarre** [comment]
the config.log of the nightly build to check if the option was inside of
not.
I guess the nightly build is not a full rebuild.

2015-12-31 12:38 GMT+01:00 Daniel Hobi notifications@github.com:

**Comment by dhobi** [comment]
Yep, sorry. I didn't realize we've got company (substring) :-). Thx for having a look at this!

**Comment by digitalLumberjack** [comment]
THe nightly was a full rebuild, until i changed the script for speed purpose on manual rebuilds. I'll make it a full rebuild again.

**Comment by nadenislamarre** [comment]
ok nice.
By the way, did you tried ccache or external tools chain to speed up the
compilation process ?
i'm interested on that if you get successfull good result, because i like
to to a full build before committing sometimes, but regularly, i just do a
delta and it's less nice. While we're just in alpha 4.0, that's ok for the
moment, but that's for later.

2015-12-31 13:24 GMT+01:00 digitalLumberjack notifications@github.com:

**Comment by digitalLumberjack** [comment]
The toolchain is already external, We just build the target, not host. Didn't tried ccache yet.

**Comment by nadenislamarre** [comment]
you mean : you have a nightly build script which does that (with a link or
a variable for the toolchain) ?
Is the nightly build script available ? Because for the moment, my way of
compiling is git status --ignored to check there is nothing or i removed,
and make config && make, so, i include all the downloading for exemple
(because some projects are from git like es)
So, it's almost 5 hours for the moment for me.

2015-12-31 13:28 GMT+01:00 digitalLumberjack notifications@github.com:

**Comment by digitalLumberjack** [comment]
I just set the host and download dirs outside of the sourcetree, and i just rm + git clone again each time i want to recompile from scratch

**Comment by nadenislamarre** [comment]
ok, nice. I'll try ccache and tell you if i win time.
(for information for people how are interested :
http://free-electrons.com/~thomas/buildroot/manual/html/ch09.html)

2015-12-31 13:51 GMT+01:00 digitalLumberjack notifications@github.com:

**Comment by dhobi** [comment]
I don't assume the new years build was a full rebuild?

**Comment by digitalLumberjack** [comment]
http://jenkins.recalbox.com/job/recalbox-4.0.0/53/ is a full rebuild

**Comment by dhobi** [comment]
Hmm...have tested every build 54+
- Kodi 14.2 RC (I thought it was 15.x on 4.0.0?)
- No SFTP option :-(

**Comment by digitalLumberjack** [comment]
Corrected this morning

**Comment by nadenislamarre** [comment]
I confirm that in my last build i've sftp listed in kodi.

**Comment by rockaddicted** [comment]
Yes and  I confirm that work very well. I'm using it since 2-3 days.

**Pull request merged**
