### PR TITLE
Remove .bin for PSX + add .cbn extension

### PR DESCRIPTION
**Pull request by paradadf**
Please make sure your PR is ready to be merged !

- [x] You added the changes in CHANGELOG.md
- [x] You choose the right repository branch to make the PR
- [x] You described the PR as below

Fixes #XXXX

Changes :
- Discussion https://forum.recalbox.com/topic/4501/remove-bin-extention-for-psx
- .cue files can be easily created if missing, the gamelist will be cleaner (no duplicates) and scraping a .cue file is lighting fast!
- Info about creating .cue file can be found [here](https://github.com/retropie/retropie-setup/wiki/playstation-1#why-arent-my-bin-files-showing-in-emulation-station)
- Allowed extensions http://wiki.libretro.com/index.php?title=PCSX_ReARMed

Related to (put here the others PR in other repositories)

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
Can one of the admins verify this patch?

**Comment by digitalLumberjack** [comment]
thanks pal

**Comment by digitalLumberjack** [comment]
@rockaddicted @substring shouldn't it be also on the 4.0 ?

**Comment by nadenislamarre** [comment]
...

Le samedi 5 novembre 2016, digitalLumberjack notifications@github.com a
écrit :

**Comment by digitalLumberjack** [comment]
You don't think it's a good idea ? We talk about it with @rockaddicted and we thought that the dual bin/cue display is really annoying and that we should have removed .bin support long ago. 
The bins always have a .cue as i know.

The issue will still be the same : the uppercase/lowercase support

**Pull request merged**
