### PR TITLE
Add a tool to generate report to be able to debug.

### PR DESCRIPTION
**Pull request by nadenislamarre**
At the end, this could be integrated to the manager.
This can be enchanced with some other files / commands.

Signed-off-by: Nicolas Adenis-Lamarre nicolas.adenis-lamarre@gmail.com

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
good idea and good job pal

We can create an issue in the manager for that.

**Comment by rockaddicted** [comment]
I love this idea too.
Could we add it in the 3.3.0 ? That will be very usefull to do support of the next official release.

**Comment by digitalLumberjack** [comment]
We can add that in unified branch.

**Comment by rockaddicted** [comment]
:+1:

**Comment by Laddyacris** [comment]
:+1:

**Comment by sveetch** [comment]
Is it really working ? I mean, to start its integration i just tested it on my linux server and it fails on something like:

```
sveetch@STA103:/recalbox$ ./recalbox-support.sh 
./recalbox-support.sh: 32: ./recalbox-support.sh: cannot create /tmp/recalbox-support-20151220004734/system/dmesg.txt: Directory nonexistent
./recalbox-support.sh: 33: ./recalbox-support.sh: cannot create /tmp/recalbox-support-20151220004734/system/lsmod.txt: Directory nonexistent
./recalbox-support.sh: 34: ./recalbox-support.sh: cannot create /tmp/recalbox-support-20151220004734/system/ps.txt: Directory nonexistent
```

**Comment by substring** [comment]
I have tested it on my 3.3.0b17, works as expected. It requises a patch to evtest

Are you rrunning it on 4.0.0 ?

**Comment by sveetch** [comment]
Could you put the builded tarball in another directory ?

Having them in the same directory than system saves is painful to manage for both of them (saves and builded tarballs).

**Comment by substring** [comment]
The aim was to have them on a smb share. I guess it could be moved to a new folder with a new smb share

**Comment by nadenislamarre** [comment]
yes. but if you want to control the output directpry and file, just give an
argument like /tmp/toto.tar.gz

**Comment by sveetch** [comment]
@nadenislamarre i may not have the last script version (i dont remember where i retrieved it, probably someone gives me an url for download) because the full path is hardcoded in the one i have. So there is no possibility to control anything from command line argument on this script.

**Pull request merged**
