### PR TITLE
Update of the readme files

### PR DESCRIPTION
**Pull request by ghost**
Please make sure your PR is ready to be merged !
- [-] You added the changes in CHANGELOG.md
- [X] You choose the right repository branch to make the PR
- [X] You described the PR as below

Fixes only the readme files

Changes :
- All links to DMCA protected content have been removed from the Englisch and French readme files in the system directories 

Related to (4.1)

Please merge this also into 4.1

### CODE REVIEW

**Comment by rockaddicted** [comment]
Hi, game and watch games are released under this license https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode

**Comment by ghost** [comment]
Are they? Sorry, didn't knew that. Shall we merge the PR nonetheless, or shall I make a new PR?

**Comment by substring** [comment]
@Nachtgarm just commit your changes in your branch 4.0-readme-update, they'll automatically be pushed in your PR

**Comment by ghost** [comment]
Done

**Review by substring — APPROVED** [review]

**Comment by rockaddicted** [comment]
@Nachtgarm thx

**Comment by substring** [comment]
OMG https://github.com/recalbox/recalbox-manager/blob/master/project/MANIFEST.xml

**Comment by ghost** [comment]
Well... that needs to be changed as well, right?

**Comment by digitalLumberjack** [comment]
thanks @Nachtgarm

**Pull request merged**
