### PR TITLE
Rb 4.1.x

### PR DESCRIPTION
**Pull request by cobba2020**
Please make sure your PR is ready to be merged !
- [x] You added the changes in CHANGELOG.md
- [x] You choose the right repository branch to make the PR
- [x] You described the PR as below

Fixes #374 
## 
- 

Related to (put here the others PR in other repositories)

### CODE REVIEW

**Comment by rockaddicted** [comment]
Hi @cobba2020 What are you trying to do with your PR ?

**Comment by cobba2020** [comment]
Hi rockaddicted, just trying to build the recalbox 4.1.. I am having a bit of trouble trying to building.

**Comment by substring** [comment]
@cobba2020 don't use the git push command pal ;) The wiki is quite clear on how to compile, you should follow it :)
Please close your pr ;)

**Comment by digitalLumberjack** [comment]
:)

**Pull request closed without merging**
